#!/usr/bin/env bash
set -euo pipefail

# shellcheck source=../lib/batch.sh
source "$(dirname "$0")/../lib/batch.sh"

BATCH_HELP_DESC="Creates GitHub issues for Stellar-K8s CI/CD passing and deduplication (Hard - 200 Points each)."
batch_parse_help "$@"

EXPECTED_ISSUE_COUNT=4
batch_validate_issue_count "$EXPECTED_ISSUE_COUNT"

echo "Creating Batch of 200-point CI/CD Issues.."

# 1. Consolidate Core CI Workflows
gh issue create --repo "$REPO" \
  --title "Consolidate and Optimize Core CI Workflows (CI, Pre-commit, Linting)" \
  --body "### 🔴 Difficulty: Hard (200 Points)

Analyze and refactor the core continuous integration pipelines (\`ci.yml\`, \`pre-commit.yml\`, \`commit-lint.yml\`) to eliminate redundant test executions and duplicate linting steps. The goal is to ensure all core tests pass 100% of the time while significantly reducing overall execution time.

### ✅ Acceptance Criteria
- Identify and remove redundant linting/testing steps across CI workflows.
- Implement a unified caching strategy for Rust dependencies and build artifacts.
- Ensure all CI/CD pipelines pass reliably on every PR and push.
- Reduce overall core CI execution time by at least 30%.
- Document the new pipeline architecture and optimization strategies used.
" --label "stellar-wave,feature,performance"

# 2. Unify Performance and Benchmark Testing Pipelines
gh issue create --repo "$REPO" \
  --title "Unify Performance and Benchmark Testing Pipelines" \
  --body "### 🔴 Difficulty: Hard (200 Points)

Currently, \`benchmark.yml\`, \`performance-regression.yml\`, and \`webhook-benchmark.yml\` duplicate significant portions of cluster setup and environment provisioning. Unify these workflows into a cohesive performance pipeline to remove redundancy and ensure reliable passing status.

### ✅ Acceptance Criteria
- Create a shared, reusable GitHub Action for performance testing environment setup.
- Deduplicate metric collection and baseline comparison logic.
- Fix any flaky tests that occasionally cause these pipelines to fail.
- Implement matrix builds where appropriate to combine test execution.
- Maintain identical test coverage while reducing the number of workflow files.
" --label "stellar-wave,feature,performance"

# 3. Streamline Release and Multi-Arch Build Processes
gh issue create --repo "$REPO" \
  --title "Streamline Release and Multi-Arch Build Processes" \
  --body "### 🔴 Difficulty: Hard (200 Points)

The \`release.yml\` and \`multiarch-build.yml\` workflows currently perform duplicate docker builds and image tagging operations. Streamline these to ensure the release process leverages the multi-arch build artifacts instead of rebuilding from scratch, guaranteeing consistent CI passes for releases.

### ✅ Acceptance Criteria
- Refactor release workflow to download and publish artifacts generated by the multi-arch workflow.
- Eliminate duplicate \`docker buildx\` steps between the two pipelines.
- Add fail-safes to ensure broken builds never get tagged for release.
- Optimize layer caching for faster multi-arch container builds.
- Verify that simulated release events pass all required checks.
" --label "stellar-wave,feature,performance"

# 4. Optimize Heavy Validation Workflows
gh issue create --repo "$REPO" \
  --title "Optimize Heavy Validation Workflows (Chaos, Soak, Operator Boot)" \
  --body "### 🔴 Difficulty: Hard (200 Points)

The long-running validation tests (\`chaos-tests.yml\`, \`soak-test.yml\`, \`verify-operator-boot.yml\`) involve redundant Kubernetes (kind) cluster provisioning and teardown steps. Centralize the e2e test infrastructure to ensure these tests pass reliably and share common setup steps.

### ✅ Acceptance Criteria
- Extract common cluster provisioning logic into a composite GitHub Action.
- Implement parallel execution for non-conflicting chaos and boot tests.
- Resolve any flakiness causing random failures in soak or chaos tests.
- Consolidate logging and artifact gathering steps across all e2e tests.
- Ensure these heavy validation workflows pass 100% of the time on main branch.
" --label "stellar-wave,feature,reliability"

echo "✅ Created 4 hard (200-point) CI/CD issues successfully!"
